apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: macroni607/taskflow:frontend-sha-2d148a04d9ca
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: 0.0.0.0
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3001
            - name: PROJECT_SERVICE_URL
              value: http://project-service:8080
            - name: TASK_SERVICE_URL
              value: http://task-service:8081
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:8000
            - name: SESSION_COOKIE_SECURE
              value: "true"
            - name: APP_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: APP_ORIGIN
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 750m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Mi
