sonar.projectName=TaskFlow
sonar.sourceEncoding=UTF-8
sonar.sources=auth-service/src,frontend/src,notification-service/app,project-service/src/main,task-service
sonar.tests=auth-service/test,frontend/test,notification-service/tests,project-service/src/test
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/target/**,**/artifacts/**,**/*_test.go
sonar.test.inclusions=**/*.test.ts,**/test_*.py,**/*Test.java,**/*_test.go
sonar.java.binaries=project-service/target/classes
sonar.java.source=21
sonar.python.version=3.13
sonar.typescript.tsconfigPaths=auth-service/tsconfig.json,frontend/tsconfig.json
