apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: taskflow
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      automountServiceAccountToken: false
      hostname: rabbitmq
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rabbitmq
          image: rabbitmq:4.1.8-management-alpine@sha256:4631fc431a8fb41e3d7449f9a18faa13ea807793b7a5224080ff505780f8d11b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: amqp
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: taskflow
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_NODENAME
              value: rabbit@rabbitmq
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
            - name: tmp
              mountPath: /tmp
          startupProbe:
            exec:
              command: [rabbitmq-diagnostics, -q, ping]
            periodSeconds: 10
            failureThreshold: 24
          readinessProbe:
            exec:
              command: [rabbitmq-diagnostics, -q, check_running]
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: [rabbitmq-diagnostics, -q, ping]
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 768Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-data
        - name: tmp
          emptyDir:
            sizeLimit: 32Mi
