apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskflow
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:17-bookworm@sha256:051f7b7b3abdd564d5d1bd1e8c4b9c1b6e77087d1dd22020ede611c096a272e0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: taskflow
            - name: POSTGRES_USER
              value: taskflow
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: shm
              mountPath: /dev/shm
          startupProbe:
            exec:
              command: [pg_isready, -U, taskflow, -d, taskflow]
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            exec:
              command: [pg_isready, -U, taskflow, -d, taskflow]
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [pg_isready, -U, taskflow, -d, taskflow]
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
