apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: taskflow
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: taskflow-gp3
  resources:
    requests:
      storage: 3Gi
